name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - pip:
    - streamlit==1.32.0
    - supabase==2.3.1
    - pandas==2.0.0
    - numpy==1.24.0
    - gotrue==1.4.1
    - postgrest-py==1.2.0
    - realtime-py==1.1.1
