name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - streamlit==1.32.0
    - supabase==2.2.6
    - pandas==2.0.0
    - numpy==1.24.0
    - gotrue==2.12.3
    - postgrest-py==1.2.0
    - realtime-py==1.1.1
    - httpx==0.24.1