SUPABASE_URL = "https://nzhjkzptsbgkdsmgoawi.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56aGprenB0c2Jna2RzbWdvYXdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTQ5OTIsImV4cCI6MjA2ODU5MDk5Mn0.HhmgKC3UXPlDpCOLdKR_d2b4swvFVilWF2xEZBy5hTw"
